**Numpy provides efficient storage
it also provide better way of handling data for processing
it is fast
it is easy to learn
Numpy uses relatively less memory to store data**

In [1]:
import numpy as np

In [2]:
myarr= np.array([2,3,54,76,75], np.int8)
myarr

array([ 2,  3, 54, 76, 75], dtype=int8)

In [3]:
myarry= np.array([[2,3,54,76,75]], np.int8)  #2d array
myarry[0,1]

3

In [4]:
myarry.shape

(1, 5)

In [5]:
myarr.dtype

dtype('int8')

#There are 5 general mechanisms for creating arrays:

***1.Conversion from other Python structures (e.g., lists, tuples)
2.Intrinsic numpy array array creation objects (e.g., arange, ones, zeros, etc.)
3.Reading arrays from disk, either from standard or custom formats
4.Creating arrays from raw bytes through the use of strings or buffers
5.Use of special library functions (e.g., random)****

***1***.

In [6]:
Listarray = np.array([[1,2,3],[3,4,5],[4,5,6]])
Listarray

array([[1, 2, 3],
       [3, 4, 5],
       [4, 5, 6]])

In [7]:
Listarray.dtype

dtype('int32')

In [8]:
Listarray.size

9

In [9]:
np.array({32,43,54})   #always use int and float type for methamatical-
                                             #-operations and avoid object.

array({32, 43, 54}, dtype=object)

***2***.

In [10]:
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
rng= np.arange(16)          #arange function gives the numpy array
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [12]:
Lspace= np.linspace(0,50,10)
Lspace

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [13]:
np.identity(34)       #identity matrix

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [14]:
emp = np.empty((2,4)) #the numpy.empty() function is used to return new array of a given shape and type. 
                   # It's just that the values are completely arbitrary.     
emp

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 7.86552508e-321, 7.56592337e-307,
        9.34588060e-307]])

In [15]:
empty= np.empty_like(Lspace)  
empty

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

empty_like() function in Python is used to return a new array with the same shape and data type as the one passed to it

In [16]:
ar= np.arange(99)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [17]:
ar.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [18]:
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [19]:
ar = ar.ravel() # to make 1d array
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [20]:
x = np.array([[1,2,5],[3,7,2],[1,4,5]])
x

array([[1, 2, 5],
       [3, 7, 2],
       [1, 4, 5]])

In [21]:
x.sum(axis=0)        # row -! downwards

array([ 5, 13, 12])

In [22]:
x.sum(axis=1)      #cloumns  ->

array([ 8, 12, 10])

In [23]:
x.T   # transpose   rows <-> columns

array([[1, 3, 1],
       [2, 7, 4],
       [5, 2, 5]])

In [24]:
x.flat       # to get all the items of an array

In [25]:
for item in x.flat:
    print(item)

1
2
5
3
7
2
1
4
5


In [26]:
x.ndim       # to show number of dimensions 

2

In [27]:
x.size     # to check how many elements in given array

9

In [28]:
x.nbytes        # to know total bytes consumed      
                  #it run as a attribute without paranthesis

36

In [29]:
one = np.array([21,434,54,65])


In [30]:
one.argmax()    # it show the index of maximum element in my array

1

In [31]:
one.argmin()       #it show the index of minimum element

0

In [32]:
one.argsort()    # it tells how your array index should be,to short you array

array([0, 2, 3, 1], dtype=int64)

In [33]:
y = np.array([[1,3,5],[3,7,2],[1,4,5]])
y

array([[1, 3, 5],
       [3, 7, 2],
       [1, 4, 5]])

In [34]:
y.argmin()

0

In [35]:
y.argmax()

4

In [36]:
y.argmax(axis=0)          #it show the index of max element  !

array([1, 1, 0], dtype=int64)

In [37]:
y.argmax(axis=1)          #->

array([2, 1, 2], dtype=int64)

In [38]:
y.argsort(axis=1)

array([[0, 1, 2],
       [2, 0, 1],
       [0, 1, 2]], dtype=int64)

In [39]:
x.reshape(9,1)

array([[1],
       [2],
       [5],
       [3],
       [7],
       [2],
       [1],
       [4],
       [5]])

**Matrix operations** :

In [40]:
ar1= np.array([[1,3,5],[3,7,2],[1,4,5]])
ar1

array([[1, 3, 5],
       [3, 7, 2],
       [1, 4, 5]])

In [41]:
ar2= np.array([[1,2,3],[4,5,6],[7,5,2]])
ar2


array([[1, 2, 3],
       [4, 5, 6],
       [7, 5, 2]])

In [42]:
ar1+ar2

array([[ 2,  5,  8],
       [ 7, 12,  8],
       [ 8,  9,  7]])

In [43]:
ar1*ar2

array([[ 1,  6, 15],
       [12, 35, 12],
       [ 7, 20, 10]])

In [44]:
np.sqrt(ar1)

array([[1.        , 1.73205081, 2.23606798],
       [1.73205081, 2.64575131, 1.41421356],
       [1.        , 2.        , 2.23606798]])

In [45]:
ar1.sum()

31

In [46]:
ar1.min()

1

In [47]:
ar2.max()

7

In [48]:
np.where(ar1>4)

(array([0, 1, 2], dtype=int64), array([2, 1, 2], dtype=int64))

In [49]:
np.count_nonzero(ar1)

9

In [50]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])